### ISSUE TITLE
A player should easily regognize his character

### ISSUE THREAD

**Issue by Tatallias** [Tatallias/heigvd-pro-a-05#28]

**Comment by gvetter** [comment]
Comment vous voulez faire ça? Je peux faire 4 sprites differentes, mais comment on les associe?

**Comment by Tatallias** [comment]
Des couleurs différentes, ou bien un indicateur vers la barre de pdv disant P1,P2 et la même chose sur le phone

**Comment by Boosterloop** [comment]
Un pseudo (affiché dans ou en-dessus de la barre de vie) ça pourrait être sympa. Si du côté de l'application android on nous demande d'entrer un pseudo et qu'il soit envoyé au serveur, par exemple au lieu d'envoyer "READY" au serveur, on envoie "READY pseudo".

**Comment by gvetter** [comment]
On regardera ça demain
